export interface ITransfer{
    TransferTypeFId     : number,
    TransferStatusFId   : number,
    CallUserFId         : number ,
    BranchFId           : number ,
    CurrencyFId         : number,
    IntervalFId         : number,
    CardFId             : number,
    FromBranchId        : number,
    ToBranchId          : number,
    Amount              : number,
    SenderName          : string,
    SenderPhone         : string,
    ReceiverName        : string,
    ReceiverPhone       : string,
    Address             : string,
    Note                : string,
    Code                : string,
    ImagePath           : string,
    Completed           : string,
    CompleteNote        : string,
    DateCompleted       : string,
    OrderNumber         : string,
    Barcode             : string,
    CardExpiryDate      : string,
    TokenPath           : string,
    Signature           : string,
    TimeCalled          : string,
    DateCreated         : string,
    UniqueString        : string
}